#!/bin/bash
# Dream Flow - Flutter Build Script
# Auto-generated by setup_automation.py

flutter build apk --release \
  --dart-define=SUPABASE_URL=https://your-project.supabase.co \
  --dart-define=SUPABASE_ANON_KEY=your-anon-key \
  --dart-define=BACKEND_URL=https://your-backend-url.com \
  --dart-define=REVENUECAT_API_KEY=appl_... or goog_... \
  --dart-define=STRIPE_PUBLISHABLE_KEY=pk_test_... \
  --dart-define=STRIPE_PREMIUM_MONTHLY_PRICE_ID=price_... \
  --dart-define=STRIPE_PREMIUM_ANNUAL_PRICE_ID=price_... \
  --dart-define=STRIPE_FAMILY_MONTHLY_PRICE_ID=price_... \
  --dart-define=STRIPE_FAMILY_ANNUAL_PRICE_ID=price_... \
  --dart-define=ADMOB_BANNER_AD_UNIT_ID=ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX \
  --dart-define=ADMOB_INTERSTITIAL_AD_UNIT_ID=ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX \
  --dart-define=ADMOB_IOS_APP_ID=ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXXXXX \
  --dart-define=ADMOB_ANDROID_APP_ID=ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXXXXX \
  --dart-define=ADSENSE_PUBLISHER_ID=pub-... \
  --dart-define=SENTRY_DSN= \
  --dart-define=ENVIRONMENT=production
